API:
  github:
    token: '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'
NOTIFICATION:
  dingtalk:
    enabled: true
    secret_key: 'SEC55720f74e664fec45b34bf2eb47a4ffbd7a560aa3abd5c41c1c4b06f7b01bcab'
    webhook_url: 'https://oapi.dingtalk.com/robot/send?access_token=917e87f96be40a493e9bd84579a8a790979d7090344bc673be71ad7e28f7854f'
  email:
    enabled: false
    password: ''
    recipients: []
    sender: cve-alert@example.com
    smtp_port: 587
    smtp_server: smtp.example.com
    username: ''
  wechat_work:
    enabled: false
    webhook_url: ''
CACHE:
  enabled: true
  dir: .cache
  ttl: 3600
  max_size: 100000000
LOGGING:
  level: INFO
  file: poc_monitor.log
  format: '%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s'
  max_bytes: 10485760
  backup_count: 5
  enable_console: true
  enable_file: true
# 特定于POC监控的数据源配置
sources:
- enabled: true
  name: Poc-Monitor_v1.0.1_update
  priority: 1
  type: json
  url: https://raw.githubusercontent.com/adminlove520/Poc-Monitor_v1.0.1/main/update.json
- enabled: true
  name: Poc-Monitor_v1.0.1_daily
  priority: 2
  type: json
  url: https://raw.githubusercontent.com/adminlove520/Poc-Monitor_v1.0.1/main/dateLog/{date}.json
- enabled: true
  name: PocOrExp_Today
  priority: 3
  type: markdown
  url: https://github.com/ycdxsb/PocOrExp_in_Github/blob/main/Today.md
- enabled: true
  name: PocOrExp_{current_year}
  priority: 4
  type: markdown
  url: https://github.com/ycdxsb/PocOrExp_in_Github/blob/main/{current_year}/README.md
