API:
  github:
    token: 'YOUR_GITHUB_TOKEN_HERE'
NOTIFICATION:
  dingtalk:
    enabled: true
    secret_key: 'YOUR_DINGTALK_SECRET_HERE'
    webhook_url: 'YOUR_DINGTALK_WEBHOOK_HERE'
  email:
    enabled: false
    password: ''
    recipients: []
    sender: cve-alert@example.com
    smtp_port: 587
    smtp_server: smtp.example.com
    username: ''
  wechat_work:
    enabled: false
    webhook_url: ''
CACHE:
  enabled: true
  dir: .cache
  ttl: 3600
  max_size: 100000000
LOGGING:
  level: INFO
  file: poc_monitor.log
  format: '%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s'
  max_bytes: 10485760
  backup_count: 5
  enable_console: true
  enable_file: true
# 特定于POC监控的数据源配置
sources:
- enabled: true
  name: Poc-Monitor_v1.0.1_update
  priority: 1
  type: json
  url: https://raw.githubusercontent.com/adminlove520/Poc-Monitor_v1.0.1/main/update.json
- enabled: true
  name: Poc-Monitor_v1.0.1_daily
  priority: 2
  type: json
  url: https://raw.githubusercontent.com/adminlove520/Poc-Monitor_v1.0.1/main/dateLog/{date}.json
